### ISSUE TITLE
Installing CentOS Atomic Host on leaseweb

### ISSUE THREAD

**Issue by alikhajeh1** [nrocco/archiso-sshd#1]
I'm following http://developer.leaseweb.com/blog/2015/04/23/provision-baremetal.html to setup CentOS Atomic Host on a dedicated server and can't figure out what I'm doing wrong:

```
curl -H "X-Lsw-Auth: $API_KEY" -X POST https://api.leaseweb.com/v1/bareMetals/123/leases -d bootFileName="http://s3.eu-central-1.amazonaws.com/setup-notes/boot.ipxe"

curl -H "X-Lsw-Auth: $API_KEY" -X POST https://api.leaseweb.com/v1/bareMetals/123/reboot
```

boot.ipxe:

```
#!ipxe
dhcp
kernel http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/vmlinuz
initrd http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-Installer.iso
boot
```

I can't ping the server, any ideas what I'm doing wrong?

**Comment by alikhajeh1** [comment]
Leaseweb pointed out my issue:
sudo livecd-iso-to-pxeboot CentOS-Atomic-Host-7-Installer.iso -> will output the following files:

[root@sadasdasdsa-8b04fce3 ~]# ls -al tftpboot/
total 828568
drwxr-xr-x 3 root root 4096 Oct 17 09:43 .
dr-xr-x--- 10 root root 4096 Oct 17 09:42 ..
-rw-r--r-- 1 root root 843246753 Oct 17 09:43 initrd.img
-rw-r--r-- 1 root root 26771 Oct 17 09:43 pxelinux.0
drwxr-xr-x 2 root root 4096 Oct 17 09:43 pxelinux.cfg
-rwxr-xr-x 1 root root 5157296 Oct 17 09:43 vmlinuz

With this you can create the PXE install:

#!ipxe
dhcp
kernel http://s3...../vmlinuz
initrd http://s3...../initrd.img
boot

**Comment by nrocco** [comment]
Hi, good to hear that your issue was resolved with the help of LeaseWeb. 

Did you manage to launch a CentOS Atomic Host?

**Comment by alikhajeh1** [comment]
Not yet with ipxe, I'm trying it with LeaseWeb's Remote Management feature next...
